/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai2;

import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ADMIN
 */
public class QLSV extends javax.swing.JFrame {
    int check = 0;
    int selectRow = -1;
    public static boolean laNamNhuan(int nYear)
    {
	if ((nYear % 4 == 0 && nYear % 100 != 0) || nYear % 400 == 0)
	{
		return true;
	}
	return false;

	
    }
   public static  int tinhSoNgayTrongThang(int nMonth, int nYear)
{
	int nNumOfDays = 0;

	switch (nMonth)
	{
	case 1:
	case 3:
	case 5:
	case 7:
	case 8:
	case 10:
	case 12: 
		nNumOfDays = 31;
		break;
	case 4:
	case 6:
	case 9:
	case 11: 
		nNumOfDays = 30;
		break;
	case 2:
		if (laNamNhuan(nYear))
		{
			nNumOfDays = 29;
		}
		else
		{
			nNumOfDays = 28;
		}
		break;
	}

	return nNumOfDays;
}
   public static boolean laNgayHopLe(int nDay, int nMonth, int nYear)
{
	// Kiểm tra năm
	if (nYear < 0)
	{
		return false; // Ngày không còn hợp lệ nữa!
	}

	// Kiểm tra tháng
	if (nMonth < 1 || nMonth > 12)
	{
		return false; // Ngày không còn hợp lệ nữa!
	}

	// Kiểm tra ngày
	if (nDay < 1 || nDay > tinhSoNgayTrongThang(nMonth, nYear))
	{
		return false; // Ngày không còn hợp lệ nữa!
	}

	return true; // Trả về trạng thái cuối cùng...
}
    /**
     * Creates new form QLSV
     */
    public QLSV() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mssv = new javax.swing.JTextField();
        tensv = new javax.swing.JTextField();
        ngaysinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        file = new javax.swing.JButton();
        csdl = new javax.swing.JButton();
        thoat = new javax.swing.JButton();
        huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sinh viên"));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setText("Mã số sinh viên");

        jLabel2.setText("Tên sinh viên");

        jLabel3.setText("Ngày sinh");

        tensv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensvActionPerformed(evt);
            }
        });

        jLabel4.setText("(dd/mm/yy)");

        add.setText("Thêm");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        save.setText("Lưu");
        save.setEnabled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        update.setText("Sửa");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Xóa");
        delete.setEnabled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(18, 18, 18)
                        .addComponent(save)
                        .addGap(32, 32, 32)
                        .addComponent(update)
                        .addGap(18, 18, 18)
                        .addComponent(delete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mssv)
                            .addComponent(tensv)
                            .addComponent(ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(save)
                    .addComponent(update)
                    .addComponent(delete))
                .addGap(30, 30, 30))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sinh viên"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số sinh viên", "Tên sinh viên", "Ngày sinh"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );

        file.setText("File");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });

        csdl.setText("CSDL");
        csdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csdlActionPerformed(evt);
            }
        });

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        huy.setText("Hủy");
        huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(file)
                .addGap(18, 18, 18)
                .addComponent(csdl)
                .addGap(55, 55, 55)
                .addComponent(huy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoat)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(file)
                    .addComponent(csdl)
                    .addComponent(thoat)
                    .addComponent(huy))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tensvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tensvActionPerformed

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        // TODO add your handling code here:
        if(file.getText().equals("File")){
            file.setText("Mở File");
            csdl.setText("Lưu File");
            csdl.setEnabled(false);
            huy.setVisible(true);
            if(jTable1.getRowCount() >= 1){
                csdl.setEnabled(true);
            }
        }
        else{
            
            JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

            int returnValue = jfc.showOpenDialog(null);
            // int returnValue = jfc.showSaveDialog(null);

            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jfc.getSelectedFile();
                String filePath = selectedFile.getAbsolutePath();
                File file = new File(filePath);
                try {
                    FileReader fr = new FileReader(file);
                    BufferedReader br = new BufferedReader(fr);
                    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                    if(jTable1.getRowCount()>0){
                        for(int i=0; i<jTable1.getRowCount();i++){
                            model.removeRow(i);
                            mssv.setText("");
                            tensv.setText("");
                            ngaysinh.setText("");
                            
                            add.setText("Thêm");
                            save.setEnabled(false);
                            update.setEnabled(false);
                            delete.setEnabled(false);
                        }
                    }
                    Object[] tableLines = br.lines().toArray();
                    for(int i=0; i < tableLines.length; i++){
                        String[] line = tableLines[i].toString().split(",");
                        model.addRow(line);
                    }
                    JOptionPane.showMessageDialog(null, "Mở file thành công!!!", "Thông báo", 1);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(QLSV.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        
        
    }//GEN-LAST:event_fileActionPerformed

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        // TODO add your handling code here:
        
        
        System.exit(0);
    }//GEN-LAST:event_thoatActionPerformed

    private void huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        if(jTable1.getRowCount()>0){
            for(int i=0; i<jTable1.getRowCount();i++){
                model.removeRow(i);
                mssv.setText("");
                tensv.setText("");
                ngaysinh.setText("");
                            
                add.setText("Thêm");
                save.setEnabled(false);
                update.setEnabled(false);
                delete.setEnabled(false);
            }
        }
        add.setText("Thêm");
        save.setEnabled(false);
        update.setEnabled(false);
        delete.setEnabled(false);
        file.setText("File");
        csdl.setText("CSDL");
        csdl.setEnabled(true);
        huy.setVisible(false);
        mssv.setText("");
        tensv.setText("");
        ngaysinh.setText("");
        
        
        
        
    }//GEN-LAST:event_huyActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        if(add.getText().equals("Thêm"))
        {
            if(mssv.getText().equals("")||tensv.getText().equals("")||ngaysinh.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this,"Mã số sinh viên, tên, ngày sinh không được để trống","Thông báo",0);
            }
            else{
                boolean flag, flag2, exists = false;
                String date = "\\d{2}/\\d{2}/\\d{4}";
                String code = "\\d{8}";
                flag = ngaysinh.getText().matches(date);
                flag2 = mssv.getText().matches(code);
                
                
                
                
                
                if(flag && flag2  )
                {   
                    String ngaythangnam=ngaysinh.getText();
                    
                    String ngay=ngaysinh.getText().substring(0,2);
                    String thang=ngaysinh.getText().substring(3,5);
                    String nam=ngaysinh.getText().substring(6,10);
                    
                    SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
                    int a= Integer.parseInt(ngay);
                    int b=Integer.parseInt(thang);
                    int c=Integer.parseInt(nam);
                    if(laNgayHopLe(a,b,c)==true)
                        {
                    for(int i=0; i<jTable1.getRowCount(); i++)
                        if(jTable1.getValueAt(i, 0).equals(mssv.getText()))
                            exists = true;
                    if(exists == false){
                        String data[] = {mssv.getText(), tensv.getText(), ngaysinh.getText()};
                        model.addRow(data);
                        add.setText("Hủy");
                        save.setEnabled(true);
                        if(csdl.getText().equals("Lưu File"))
                            csdl.setEnabled(true);
                        mssv.setFocusable(false);
                        mssv.setFocusable(false);
                        ngaysinh.setFocusable(false);
                    }
                    else
                        JOptionPane.showMessageDialog(this, "Mã số sinh viên " + mssv.getText() + " đã tồn tại", "Thông báo", 2);
                    }else
                    if(laNgayHopLe(a,b,c)==false)
                        JOptionPane.showMessageDialog(this, "Ngày không hợp lệ", "Thông báo", 2);
                    else
                        JOptionPane.showMessageDialog(this, "Mã số sinh viên sai định dạng", "Thông báo", 2);
                
                
                }
                else
                    if(!flag && flag2)
                        JOptionPane.showMessageDialog(this, "Ngày sai định dạng", "Thông báo", 2);
                    else
                        JOptionPane.showMessageDialog(this, "Mã số sinh viên sai định dạng", "Thông báo", 2);
            }
        }
        else{
            mssv.setText("");
            tensv.setText("");
            ngaysinh.setText("");
            mssv.setFocusable(true);
            tensv.setFocusable(true);
            ngaysinh.setFocusable(true);
            add.setText("Thêm");
            update.setEnabled(false);
            delete.setEnabled(false);
        }
    }//GEN-LAST:event_addActionPerformed

    private void csdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csdlActionPerformed
        // TODO add your handling code here:
        
        if(csdl.getText().equals("Lưu File")){
            try{
                JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

                int returnValue = jfc.showSaveDialog(null);

                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = jfc.getSelectedFile();
                    String filePath = selectedFile.getAbsolutePath();

                    File file = new File(filePath);
                    while(file.exists() && !file.isDirectory()){
                        if(JOptionPane.showConfirmDialog(null, "File đã tồn tại. Bạn có muốn ghi đè lên không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                            file.createNewFile();
                            break;
                        }
                        else{
                            returnValue = jfc.showSaveDialog(null);
                            if (returnValue == JFileChooser.APPROVE_OPTION) {
                                selectedFile = jfc.getSelectedFile();
                                filePath = selectedFile.getAbsolutePath();

                                file = new File(filePath);
                            }
                        } 
                    }
                    FileWriter fw = new FileWriter(file.getCanonicalFile());
                    BufferedWriter bw = new BufferedWriter(fw);

                    for(int i=0; i<jTable1.getRowCount(); i++){
                        for(int j=0; j<jTable1.getColumnCount(); j++){
                            bw.write((String)jTable1.getModel().getValueAt(i, j)+",");
                        }
                        bw.write("\n");
                    }
                    JOptionPane.showMessageDialog(this, "Lưu file thành công", "Thông báo", 1);
                    bw.close();
                    fw.close();
                    
                }
            }
            catch(Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_csdlActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(check == 1){
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            String Mssv = mssv.getText();
            String Name = tensv.getText();
            String date = ngaysinh.getText();

            model.setValueAt(Mssv, jTable1.getSelectedRow(), 0);
            model.setValueAt(Name, jTable1.getSelectedRow(), 1);
            model.setValueAt(date, jTable1.getSelectedRow(), 2);

            JOptionPane.showMessageDialog(this, "Đã lưu thay đổi", "Thông báo", 1);
            
            mssv.setFocusable(false);
            tensv.setFocusable(false);
            ngaysinh.setFocusable(false);
            save.setEnabled(false);
        }
        
        
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        
        if(selectRow != -1){
            if(JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa sinh viên "+mssv.getText()+" không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                model.removeRow(selectRow);
                selectRow = jTable1.getSelectedRow();
                mssv.setText("");
                tensv.setText("");
                ngaysinh.setText("");
            }
            delete.setEnabled(false);
            update.setEnabled(false);
            add.setText("Thêm");
            mssv.setFocusable(true);
            tensv.setFocusable(true);
            ngaysinh.setFocusable(true);
            selectRow = -1;
        }
        else
            JOptionPane.showMessageDialog(this, "Bạn vui lòng chọn sinh viên trong danh sách!!!", "Thông báo", 2);
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
        if(jTable1.getSelectedRowCount() == 1){
            check = 1;
            mssv.setFocusable(true);
            tensv.setFocusable(true);
            ngaysinh.setFocusable(true);
            mssv.requestFocus();
            save.setEnabled(true);
        }
        else
            JOptionPane.showMessageDialog(this, "Bạn vui lòng chọn 1 sinh viên trong danh sách!!!", "Thông báo", 2);
    }//GEN-LAST:event_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selectRow = jTable1.getSelectedRow();
        mssv.setText((String)jTable1.getValueAt(selectRow, 0));
        tensv.setText((String)jTable1.getValueAt(selectRow, 1));
        ngaysinh.setText((String)jTable1.getValueAt(selectRow, 2));
        mssv.setFocusable(false);
        tensv.setFocusable(false);
        ngaysinh.setFocusable(false);
        add.setText("Hủy");
        save.setEnabled(false);
        update.setEnabled(true);
        delete.setEnabled(true);
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static  boolean kiemtra(String ngay,String thang,String nam)
    {  
        
        int a= Integer.parseInt(ngay);
        int b=Integer.parseInt(thang);
        int c=Integer.parseInt(nam);
        if(c<=0)
            return false;
        else if(b<=0||b>=13)
            return false;
        else if(((b==1||b==3||b==5||b==7||b==8||b==10||b==12)&&(a!=31))||((b==4||b==6||b==9||b==11)&&(a!=30)))
                return false;
        else if((((c%4==0&&c%100!=0)||c%400==0))&&a!=29)
            return false;
        else if(a!=28)
                return false;
     return true;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV().setVisible(true);
                huy.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton csdl;
    private javax.swing.JButton delete;
    private javax.swing.JButton file;
    private static javax.swing.JButton huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mssv;
    private javax.swing.JTextField ngaysinh;
    private javax.swing.JButton save;
    private javax.swing.JTextField tensv;
    private javax.swing.JButton thoat;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
